"""added comment column to SavedRecipe

Revision ID: 48691b07e9b9
Revises: 2846603b462d
Create Date: 2023-10-13 14:40:45.016626

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48691b07e9b9'
down_revision = '2846603b462d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saved_recipes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comment', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saved_recipes', schema=None) as batch_op:
        batch_op.drop_column('comment')

    # ### end Alembic commands ###
