"""added servings to recipe model

Revision ID: 56775d483918
Revises: d5c57cf91b5c
Create Date: 2023-10-13 14:30:19.673226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56775d483918'
down_revision = 'd5c57cf91b5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('servings', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('keeps_for', sa.String(), nullable=True))
        batch_op.drop_column('exp_date')
        batch_op.drop_column('priority')
        batch_op.drop_column('is_perishable')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_perishable', sa.BOOLEAN(), nullable=False))
        batch_op.add_column(sa.Column('priority', sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column('exp_date', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('keeps_for')
        batch_op.drop_column('servings')

    # ### end Alembic commands ###
