"""changed storage_status placement in the tables

Revision ID: 67589f1bc3c8
Revises: f8a3870e734e
Create Date: 2023-10-13 14:00:22.439743

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67589f1bc3c8'
down_revision = 'f8a3870e734e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingredients', schema=None) as batch_op:
        batch_op.drop_column('storage_status')

    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.alter_column('cuisine',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.drop_column('storage_status')

    with op.batch_alter_table('user_ingredients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('storage_status', sa.String(), nullable=True))

    with op.batch_alter_table('user_recipes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('storage_status', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_recipes', schema=None) as batch_op:
        batch_op.drop_column('storage_status')
        batch_op.drop_column('quantity')

    with op.batch_alter_table('user_ingredients', schema=None) as batch_op:
        batch_op.drop_column('storage_status')

    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('storage_status', sa.VARCHAR(), nullable=False))
        batch_op.alter_column('cuisine',
               existing_type=sa.VARCHAR(),
               nullable=False)

    with op.batch_alter_table('ingredients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('storage_status', sa.VARCHAR(), nullable=False))

    # ### end Alembic commands ###
