"""empty message

Revision ID: a4d9342caf41
Revises: 6b1fabfaf40a
Create Date: 2023-10-18 13:50:27.064176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4d9342caf41'
down_revision = '6b1fabfaf40a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recipe_posts')
    op.drop_table('user_recipes')
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author_id', sa.String(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_recipes_author_id_users'), 'users', ['author_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_recipes_author_id_users'), type_='foreignkey')
        batch_op.drop_column('author_id')

    op.create_table('user_recipes',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('recipe_id', sa.INTEGER(), nullable=True),
    sa.Column('quantity', sa.INTEGER(), nullable=True),
    sa.Column('storage_status', sa.VARCHAR(), nullable=True),
    sa.Column('priority', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], name='fk_user_recipes_recipe_id_recipes'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_user_recipes_user_id_users'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recipe_posts',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('recipe_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], name='fk_recipe_posts_recipe_id_recipes'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_recipe_posts_user_id_users'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
