"""removed priority column from ingredients

Revision ID: cf44b0dd88a5
Revises: 56775d483918
Create Date: 2023-10-13 14:37:30.209057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf44b0dd88a5'
down_revision = '56775d483918'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingredients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('keeps_for', sa.String(), nullable=True))
        batch_op.drop_column('exp_date')
        batch_op.drop_column('priority')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingredients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('priority', sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column('exp_date', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('keeps_for')

    # ### end Alembic commands ###
