"""further edited tables

Revision ID: d5c57cf91b5c
Revises: 67589f1bc3c8
Create Date: 2023-10-13 14:18:39.846432

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5c57cf91b5c'
down_revision = '67589f1bc3c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saved_recipes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_currently_saved', sa.Boolean(), nullable=True))

    with op.batch_alter_table('user_ingredients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('priority', sa.String(), nullable=True))

    with op.batch_alter_table('user_recipes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('priority', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_recipes', schema=None) as batch_op:
        batch_op.drop_column('priority')

    with op.batch_alter_table('user_ingredients', schema=None) as batch_op:
        batch_op.drop_column('priority')

    with op.batch_alter_table('saved_recipes', schema=None) as batch_op:
        batch_op.drop_column('is_currently_saved')

    # ### end Alembic commands ###
