"""added subategory column to Ingredient class

Revision ID: ffae981d1d51
Revises: 9d24b8358a72
Create Date: 2023-10-17 17:22:28.475250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffae981d1d51'
down_revision = '9d24b8358a72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingredients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subcategory', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingredients', schema=None) as batch_op:
        batch_op.drop_column('subcategory')

    # ### end Alembic commands ###
